---
- name: Importer CSV depuis une URL
  hosts: localhost
  gather_facts: true 
  vars:
    local_csv_path: "/tmp/temperature.csv"
    temperatures_list: "{{ lookup('csvfile', \"/tmp/temperature.csv delimiter=,\") }}"
    
  tasks:
    - name: Lire le fichier CSV de températures
      ansible.builtin.read_csv:
        path: "{{ local_csv_path }}" 
        delimiter: ','
      register: temp_data

    - name: Supprimer les doublons et trier par heure
      ansible.builtin.set_fact:
        temp_cleaned: "{{ temp_data.list | unique | sort(attribute='time') }}"

    - name: Afficher les données nettoyées
      ansible.builtin.debug:
        var: temp_cleaned

