---
- name: Importer CSV depuis une URL
  hosts: localhost
  gather_facts: true 
  vars:
    local_csv_path: "/tmp/temperature.csv"
    temperatures_list: "{{ lookup('csvfile', \"/tmp/temperature.csv delimiter=,\") }}"
    
  tasks:
    - name: Afficher le contenu de la variable temperatures_list
      ansible.builtin.debug:
        msg: "À {{ item.time }}, il fait {{ item.temperature }} °C"
      loop: "{{ temperatures_list }}"
