- name: Install Apache et PHP
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - php-mysql
      - libapache2-mod-php
    state: present
    update_cache: yes

      #- name: Apache rewrite module
      #ansible.builtin.command: a2enmod rewrite
      #notify: Restart apache

- name: Demarre Apache
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: yes

- name: Verifie si /var/www/html existe
  ansible.builtin.file:
    path: /var/www/html
    state: directory

- name: Pose des permissions
  ansible.builtin.file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

- name: Restart apache
  systemd:
    name: apache2
    state: restarted
