- name: Install Apache et PHP
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - php-mysql
      - libapache2-mod-php
    state: present
    update_cache: true

- name: Demarre Apache
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: true

- name: Verifie si /var/www/html existe
  ansible.builtin.file:
    path: /var/www/html
    state: directory

- name: Pose des permissions
  ansible.builtin.file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: true

- name: Restart apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted
