- name: Download WordPress
  get_url:
    url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: true

- name: Set ownership
  ansible.builtin.file:
    path: /var/www/html/
    owner: www-data
    group: www-data
    recurse: true

- name: Depose du fichier wp-config.php
  ansible.builtin.template:
    src: wp-config-sample.php.j2
    dest: /var/www/html/wordpress/wp-config.php
