all:
  children:
    apache2:
      hosts:
        node01:
          ansible_host: 10.0.0.88
          ansible_user: root
        node02:
          ansible_host: 10.0.0.89 
          ansible_user: root 
        node03:
          ansible_host: 10.0.0.90 
          ansible_user: root 
