all:
  children:
    apache2:
      hosts:
        node01:
          ansible_host: 10.0.0.88
          ansible_user: root
        node02:
          ansible_host: 10.0.0.89
          ansible_user: root
    mysql:
      hosts:
        node01:
          ansible_host: 10.0.0.88
          ansible_user: root
        node02:
          ansible_host: 10.0.0.89
          ansible_user: root
    git:
      hosts:
        node03:
          ansible_host: 10.0.0.90
          ansible_user: root
    nginx:
      hosts:
        node03:
          ansible_host: 10.0.0.90
          ansible_user: root
    cowsay:
      hosts:
        node03:
          ansible_host: 10.0.0.90
          ansible_user: root 
