---
- name: Installer apache2 et mysql-server sur tous les serveurs
  hosts: all 
  become: yes
  tasks:
    - name: Installer des packages apache2
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
      when:
        - inventory_hostname in groups['apache2']

    - name: Installer des packages mysql-server
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server 
      when:
        - inventory_hostname in groups['mysql']

    - name: Installer des packages git
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git 
      when:
        - inventory_hostname in groups['git']

    - name: Installer des packages nginx
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx 
      when:
        - inventory_hostname in groups['nginx']

    - name: Installer des packages cowsay
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - cowsay 
      when:
        - inventory_hostname in groups['cowsay']

    - name: Installer ufw sur ubuntu
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - ufw
      when:
        - ansible_distribution|string == 'Ubuntu'

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Copy index.html if apache2 is installed
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: '0644'
      when:
        - "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"

    - name: Restart apache2 et nginx
      ansible.builtin.service:
        name: "{{ item }}" 
        state: restarted 
        enabled: yes
      loop:
        - apache2
        - nginx
      when:
        - inventory_hostname in groups['nginx']
        - inventory_hostname in groups['apache2']
