---
- name: Installer apache2 et mysql-server sur tous les serveurs
  hosts: serveurs 
  become: yes
  tasks:
    - name: verifier install apache2
      ansible.builtin.stat:
        path: /var/www/html/index.html
      register: apache2_installe

    - name: Installer des packages 
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server
      when: apache2_installe.stat.exists == False

    - name: Modifier /var/www/html/index.html si apache2 est installé
      ansible.builtin.copy:
        content: "Bonjour depuis Ansible\n"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: apache2_installe.stat.exists == False 

    - name: Star apache2
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
      when: apache2_installe.stat.exists == False
